import { Schema } from 'mongoose';

export const StatisticSchema = new Schema({
  disease: {
    type: Schema.Types.ObjectId,
    ref: 'Cid',
  },
  cid: { type: String, required: true },
  year: { type: String, required: true },
  cost_year: { type: Number, default: null },
  cost_per_case: { type: Number, default: null },
  age: { type: Number, default: null },
  mortality: { type: Number, default: null },
  mortality_rate: { type: Number, default: null },
  days_hospitalized: { type: Number, default: null },
  cases: { type: Number, default: null },
  cases_female: { type: Number, default: null },
  cases_male: { type: Number, default: null },
  cases_sp: { type: Number, default: null },
  cases_undefined_gender: { type: Number, default: null },
  cases_white: { type: Number, default: null },
  cases_black: { type: Number, default: null },
  cases_yellow: { type: Number, default: null },
  cases_brown: { type: Number, default: null },
  cases_indigenous: { type: Number, default: null },
  cases_undefined_race: { type: Number, default: null },
  percent_female: { type: Number, default: null },
  percent_male: { type: Number, default: null },
  percent_sp: { type: Number, default: null },
  percent_white: { type: Number, default: null },
  percent_black: { type: Number, default: null },
  percent_yellow: { type: Number, default: null },
  percent_brown: { type: Number, default: null },
  percent_indigenous: { type: Number, default: null },
});
