name: buscasus

static_sites:
- name: frontend
  build_command: yarn build
  environment_slug: gatsby
  github:
    repo: hugofabricio/fiap-datasus
    branch: main
    deploy_on_push: true
  source_dir: frontend
  routes:
  - path: /

services:
- name: api
  environment_slug: node-js
  github:
    repo: hugofabricio/fiap-datasus
    branch: main
    deploy_on_push: true
  source_dir: api
  routes:
  - path: /api

region: nyc